# Generated by Django 5.0.6 on 2024-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='books-images')),
                ('author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('pages', models.IntegerField()),
                ('ebook', models.FileField(blank=True, null=True, upload_to='ebooks')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
    ]
